kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: nodejs-gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
