kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    description: "Hack: Manually build the imagestream"
  name: nodejs-gitops-build
  labels:
    app: nodejs-gitops
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "nodejs-gitops:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "nodejs:14-ubi8"
      env:
        - name: NPM_MIRROR
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/redhat-capgemini-exchange/nodejs-rest"
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
