kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: noop
spec:
  params:
    - name: msg
      description: The message to print
      type: string
  steps:
    - name: msg
      image: image-registry.openshift-image-registry.svc:5000/nodejs-gitops-pipeline/gitops-cli:latest
      script: |
        #!/usr/bin/env bash

        echo "noop says: $(params.msg)"
