kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: tag-image
spec:
  params:
    - name: commit
      description: The git commit SHA
      type: string
    - name: IMAGE_NAME
      description: The name of the imagestream
      type: string
    - name: REF
      description: The git ref from the webhook payload
      type: string
    - name: NAMESPACE
      description: The namespace the imagestream is in
      type: string
  steps:
    - name: tag-image
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        IFS="/" read -a branchref <<< "$(params.REF)"

        echo "adding tag $(params.IMAGE_NAME):$(params.commit)"

        oc tag "$(params.IMAGE_NAME)":latest "$(params.IMAGE_NAME)":"$(params.commit)" -n "$(params.NAMESPACE)"

        echo "adding tag $(params.IMAGE_NAME):${branchref[-1]}"

        oc tag "$(params.IMAGE_NAME)":latest "$(params.IMAGE_NAME)":"${branchref[-1]}" -n "$(params.NAMESPACE)"
