apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: github-update-deployment
  labels:
    operator.tekton.dev/provider-type: community
spec:
  description: This task can be used to update image digest in a Git repo using kustomize
  params:
    - name: MANIFESTS_GIT
      type: string

    - name: GIT_REVISION
      type: string
    - name: GIT_BRANCH_REF
      type: string
    - name: GIT_PUSHER_NAME
      type: string
    - name: GIT_PUSHER_EMAIL
      type: string
    - name: GIT_COMMIT_MESSAGE
      type: string

    - name: CURRENT_IMAGE
      type: string
    - name: NEW_IMAGE
      type: string
    - name: NEW_DIGEST
      type: string
    - name: KUSTOMIZATION_PATH
      type: string
      
  results:
    - name: commit
      description: The commit SHA

  stepTemplate:
    envFrom:
      - secretRef:
          name: github-secrets

  steps:
    - name: validate-github
      image: image-registry.openshift-image-registry.svc:5000/nodejs-gitops-pipeline/gitops-cli:latest
      workingDir: $(workspaces.manifest.path)
      script: |
        echo "-> Validating authentication against github.com"

        gh auth status
      
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source

    - name: git-clone-manifest
      image: image-registry.openshift-image-registry.svc:5000/nodejs-gitops-pipeline/gitops-cli:latest
      workingDir: $(workspaces.manifest.path)
      
      script: |
        # setup git and gh
        echo "-> setup git and gh"

        git config --global user.email "$(params.GIT_PUSHER_EMAIL)"

        git config --global user.name "$(params.GIT_PUSHER_NAME)"

        git config pull.rebase true

        gh auth setup-git

        # extract the branch ref
        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"
        
        BRANCH="${branchref[-1]}"

        # clone the repo
        echo "-> cloning $(params.MANIFESTS_GIT)"

        rm -rf manifest-workdir

        git clone $(params.MANIFESTS_GIT) manifest-workdir

        cd manifest-workdir

        git checkout -b $BRANCH

        git pull origin $BRANCH

        PR="pr-$(params.GIT_REVISION)"

        git checkout -b $PR

      volumeMounts:
        - mountPath: /gen-source
          name: gen-source

    - name: create-patch
      image: image-registry.openshift-image-registry.svc:5000/nodejs-gitops-pipeline/gitops-cli:latest
      workingDir: $(workspaces.manifest.path)
      
      script: |
        # extract the branch ref
        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"
        
        BRANCH="${branchref[-1]}"

        PR="pr-$(params.GIT_REVISION)"

        # patch
        echo "-> patching $(params.MANIFESTS_GIT)"

        cd manifest-workdir

        pwd

        ls

      volumeMounts:
        - mountPath: /gen-source
          name: gen-source

  workspaces:
    - mountPath: /workspace/manifest
      name: manifest
  volumes:
    - emptyDir: {}
      name: gen-source
  
    