kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: tag-image-stream
spec:
  params:
    - name: GIT_REVISION
      type: string
    - name: GIT_BRANCH_REF
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: IMAGE_NAME
      type: string
    - name: NAMESPACE
      type: string

  steps:
    - name: tag-image
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"

        echo "adding tag $(params.IMAGE_NAME):$(params.GIT_REVISION)"

        oc tag "$(params.IMAGE_NAME)":latest "$(params.IMAGE_NAME)":"$(params.GIT_REVISION)" -n "$(params.NAMESPACE)"

        echo "adding tag $(params.IMAGE_NAME):${branchref[-1]}"

        oc tag "$(params.IMAGE_NAME)":latest "$(params.IMAGE_NAME)":"${branchref[-1]}" -n "$(params.NAMESPACE)"
