kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: noop
spec:
  params:
    - name: msg
      description: The message to print
      type: string
  steps:
    - name: msg
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        echo "noop says: $(params.msg)"
