kind: Namespace
apiVersion: v1
metadata:
  name: nodejs-gitops-pipeline
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: build-pipeline
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  destination:
    namespace: nodejs-gitops-pipeline
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: pipelines/build
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-gitops
    targetRevision: main
--- 
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: rollout-pipeline
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  destination:
    namespace: nodejs-gitops-pipeline
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: pipelines/rollout
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-gitops
    targetRevision: main
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs-dev-pipeline-rolebinding
  namespace: nodejs-gitops-develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: nodejs-gitops-pipeline
