kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs-develop-pipeline-rolebinding
  namespace: nodejs-rest-develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: devsecops-config
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs-release-pipeline-rolebinding
  namespace: nodejs-rest-release
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: devsecops-config
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs-main-pipeline-rolebinding
  namespace: nodejs-rest-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: devsecops-config
