kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs-release-image-puller-rolebinding
  namespace: nodejs-rest-develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-puller"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: nodejs-rest-release
