apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rollout-pipeline
spec:
  params:
    - name: APP_NAME
      type: string
      default: "nodejs-gitops"
    - name: GIT_REVISION
      type: string
      default: develop
    - name: GIT_BRANCH_REF
      type: string
      default: "foo/bar/develop"

  workspaces:
    - name: rollout

  tasks:
    
    - name: noop
      taskRef:
        kind: Task
        name: noop
      params:
      - name: msg
        value: "$(params.APP_NAME) - $(params.GIT_REVISION) - $(params.GIT_BRANCH_REF)"
      when:
        - input: $(params.GIT_BRANCH_REF)
          operator: in 
          values: ["refs/heads/release","refs/heads/main"]
      
        