apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rollout-pipeline
spec:
  params:
    - name: APP_NAME
      type: string
      default: "nodejs-gitops"

  workspaces:
    - name: rollout

  tasks:
    
    - name: noop
      params:
      - name: msg
        value: $(params.APP_NAME)
      taskRef:
        kind: Task
        name: noop
        