kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: default-app-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
status: {}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-config-dev
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  destination:
    namespace: nodejs-gitops-dev
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: app/develop
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-gitops
    targetRevision: develop
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-config-qa
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  destination:
    namespace: nodejs-gitops-qa
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: app/release
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-gitops
    targetRevision: release
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-config-prod
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  destination:
    namespace: nodejs-gitops
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: true
    path: app/main
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-gitops
    targetRevision: main