kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: default-app-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
status: {}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nodejs-gitops-config
  namespace: openshift-gitops
spec:
  project: default-app-project
  revisionHistoryLimit: 3
  destination:
    namespace: "*"
    server: https://kubernetes.default.svc
  source:
    directory:
      recurse: false
    path: app/config
    repoURL: https://github.com/redhat-capgemini-exchange/nodejs-rest-config
    targetRevision: main
